name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "5 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: IshwaranRudhara
          template: classic
          base: metadata
          config_timezone: Asia/Kolkata
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_selector: body
          plugin_screenshot_title:
          plugin_screenshot_url: https://IshwaranRudhara.github.io/random-flag-generator/dist/index.html
